### ISSUE TITLE
הערות דורית - לא מובן

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#1]
5. באג בחישוב סה"כ כמות עצים
6. עדיפות למימוש טולטיפ על הקיים
8. באג מועצות מקומיות - עדיפות לתיקון ("בואו נעשה את ג'לגוליה ירוקה")

**Comment by akariv** [comment]
מה זה 6?

**Comment by dorit102** [comment]
6- לא לחכות עד שהיה את כל הפונקציונליות, אלא לממש tooltip על מה שכבר יש כי יתלוננו על זה
