### ISSUE TITLE
 מצב עצים: גרף ->טולטיפ עם מס' העצים של כל בר ואחוזים

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#14]
<img width="278" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/a836bbd1-9df8-4cf4-afd3-63e10da6d1c1">

אפשר גם להחליף לפאי, מה שהיה יותר נכון כאמצעי להצגה, אבל אז זה יהיה פאי יחידי באתר ולכן זה בסדר לשמור על זה ככה לדעתי

**Comment by akariv** [comment]
פאי משמש רק במקרה בו רוצים להציג חלק אחד מתוך השלם:

https://www.linkedin.com/pulse/%D7%92%D7%A8%D7%A3-%D7%A2%D7%95%D7%92%D7%94-%D7%91%D7%93%D7%A9%D7%91%D7%95%D7%A8%D7%93%D7%99%D7%9D-%D7%9B%D7%9F-%D7%90%D7%95-%D7%9C%D7%90-bella-gotie-infoserviz-/
