### ISSUE TITLE
לוגיקת הצלבת עצים

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#17]
הצלבת עצי ליפי ומפ"י, לדעתי זה אותו עץ - אפשר ללמוד משהו מזה חוץ מהדיוק של ליפי? דרך אגב אני רואה שמס' הספרות בקוארדינטות לא זהה. זה קשור לדיוק?

<img width="946" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/b95fabaa-a75e-4084-a0c3-72af1d07110d">

<img width="758" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/d72bf66f-f75d-4060-b16e-dbb9c112c598">

**Comment by akariv** [comment]
מה המרחק בין שתי הקואורדינטות (במטרים)?

**Comment by akariv** [comment]
לשימושך - https://www.calculator.net/distance-calculator.html?type=3&la1=35.2208&lo1=31.77334&la2=35.22083&lo2=31.77331&ctype=dec&lad1=38&lam1=53&las1=51.36&lau1=n&lod1=77&lom1=2&los1=11.76&lou1=w&lad2=39&lam2=56&las2=58.56&lau2=n&lod2=75&lom2=9&los2=1.08&lou2=w&x=49&y=20#latlog

כיוון שהמרחק הוא מעל 3 מטרים, הנקודות האלו לא מאוחדות.
