### ISSUE TITLE
סינון מרובה סוגי עצים

### ISSUE THREAD

**Issue by akariv** [hasadna/treebase-app#22]

**Comment by emrib** [comment]
מוסיף שצריך גם הלימה לת"ז עץ שם כתוב סוג העץ. לא חושב שצריך לשנות את הקופי של הת"ז כי סוג זה גם מונח טקסטנטמי בוטני וגם ברור מספיק למשתמש הלא מקצועי. 

מציע אוטוקומפליט עם דרופדאון:
לחצתי על החלון נפתחה הרשימה כמו שהיא עם אפשרות גלילה
כתבתי ברוש
מופיעים כל סוגי הברוש לפי הסדר הקיים 
מעליהם מופיע ברוש מודגש "סוג: ברוש"
אם בחרתי סוג, כל המינים נבחרו בבחירה מרובה

**Comment by akariv** [comment]
אין לנו את שמות הסוגים נכון להיום, רק את שמות המינים.

**Comment by akariv** [comment]
(גם בממשק נצטרך לתקן שיופיע מין - זה היה בלבול שלי)
