### ISSUE TITLE
הצגת מידע נוסף על העץ, במידה וקיים בחלונית המידע

### ISSUE THREAD

**Issue by akariv** [hasadna/treebase-app#23]
מיקום גיאוגרפי (כולל כתובת, אם קיימת)
מטאדאטה: רק מזהה פנימי (אם יש)
מאפיינים פיזיים של העץ
מאפיינים סביבתיים של העץ
מאפיינים אנושיים של העץ
תמונות העץ

**Comment by emrib** [comment]
הוספת יחידות. הטולטיפ הקיים מצויין ומאוד מועיל 
לדעתך גם בטולטיפ או בסוגריים
