### ISSUE TITLE
הורדת קוסץ באקסל - מתן שם לקובץ

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#28]
האם ניתן לקרוא לקובץ tree_base_ download  או שם דומה?
כנ"ל לגבי תאריך ההורדה בפורמט 20230719 או משהו?

**Comment by akariv** [comment]
שים לב שיש כבר אישיו פתוח למשימה הזו

**Comment by akariv** [comment]
duplicate of #24
