### ISSUE TITLE
במקום א"ס לכתוב אזורים סטטיסטיים 

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#3]
מבין שיש בעיית נדל"ן בבר, חלופות:
- לכתוב שכונות ובטולטיפ לכתוב אזורים סטטיסטיים
- לכתוב אחד מעל השני בפונט קטן יותר
- לכתוב א.סטטיסטיים

**Comment by akariv** [comment]
שיניתי ל-״איזורים״, כך שיש:

רשויות
איזורים
עצים

**Comment by emrib** [comment]
מקובל, לכתוב "אזורים" (בלי י')  ולכתוב "אזורים סטטיסטיים" בכותרת בחלונית מידע
https://hebrew-academy.org.il/keyword/%D7%90%D6%B5%D7%96%D7%95%D6%B9%D7%A8/
