### ISSUE TITLE
תוכן חלון פתיחה - להמתין לאחר אישור קלינר בשל תנאי שימוש

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#4]
כותרת: 
הגעת ליע"ד!

תוכן:
ביער עירוני דיגיטלי (יע"ד) אספנו וריכזנו נתונים על 2,868,551 עצי היער העירוני של ??? רשויות מקומיות בישראל. לראשונה ניתן להציג, להשוות ולשתף מידע ארצי ועד העץ הבודד.

כניסה והסכמה לתנאי שימוש (כאן צריך לשאול את קלינגר)

**Comment by akariv** [comment]
אמרי, העברתי את המשימה אליך - תעביר אלי כשהיא מוכנה.

**Comment by emrib** [comment]
יש לך קישור לתת לטובת קלינגר של הרמה הראשונה של אנליטקס? הוא רוצה תשובה מפורטת @akariv

**Comment by akariv** [comment]
https://support.google.com/analytics/answer/11593727?hl=en

להתעלם ממה שכתוב על apps.

בנוסף,  enhanced measurement events לא מופעל אצלנו.

**Comment by emrib** [comment]
העברתי אלייך.

קישור לעמוד קנבה להטמיע בחלונית מידע של הכניסה וכקישור נוסף בסרגל העליון:
https://www.canva.com/design/DAFq4RFoMew/bcL0Ro4okQlDrF9HZ85T_g/edit

יקרא : מדיניות שימוש

**Comment by akariv** [comment]
עדכנתי את הקישור למרות שהוא לא מוביל לשום מקום.

**Comment by emrib** [comment]
קישור חדש: https://data-city.my.canva.site/terms
