### ISSUE TITLE
מיקרוקופי:  לכתוב במצב אזורים "תצוגת אזורים סטטסיטים" ולא רק "תצוגת אזורים"

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#41]
<img width="909" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/451ffbdc-744b-4615-8dc3-7841ed5a7ae8">

**Comment by akariv** [comment]
נראה לי שגם זה לא ממש ברור.

אולי נחליף ל-״צביעה:״? מה דעתך?

**Comment by emrib** [comment]
לא הבנתי

**Comment by akariv** [comment]
ככה -
<img width="236" alt="Screen Shot 2023-07-20 at 12 09 47" src="https://github.com/hasadna/treebase-app/assets/265333/3efc9a04-78b5-43fc-a7c7-aea318edd826">
<img width="250" alt="Screen Shot 2023-07-20 at 12 09 51" src="https://github.com/hasadna/treebase-app/assets/265333/7eed6b6a-a799-42ff-ae86-a4781fe4da14">

אפשר גם ״צביעת שטחים:״

**Comment by emrib** [comment]
לדעתי זה יבלבל. יותר טוב רק "הצגה" (view  או dispaly)
