### ISSUE TITLE
טאבים לסרגל העליון

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#42]
מימין לשמאל:
מתודולוגיה - https://data-city.my.canva.site/digital-forest-methodology
הוספת עצים - https://data-city.my.canva.site/digital-forest-add-trees
אודות -https://www.digital-forest.org.il/

אודה אם תוכל לשנות עד יום שני כשנציג לאנדי ומרכז העצים גם אם לא אעביר את הדפים החסרים.

**Comment by akariv** [comment]
״אודות״ כרגע פותח את חלונית המידע המופיעה בכניסה ראשונה (יש דרישה כזו),
נראה לי שכדאי להשאיר.

יש כרגע קישור ״עוד על הפרויקט״ שמוביל לדף הנחיתה.

**Comment by akariv** [comment]
(תעביר אלי בבקשה כשהאישיו מוכן לעבודה).

**Comment by emrib** [comment]
<img width="363" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/41f929dd-0fc7-4b53-b347-32e409ea7b26">
<img width="427" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/9c030ebc-0e30-4940-84fa-2f5dd8f59e49">

**Comment by emrib** [comment]
תודה@akariv הי, עידכנתי את הקישורים לסרגל העליון.  אודה אם זה יהיה למחר.
