### ISSUE TITLE
סינון לפי מין העץ

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#47]
באיפיון כתוב:
סינון לפי מין העץ (בחירת ערך מרשימה - TBD אפיון מדויק, יש הרבה מאוד ערכים, אולי נצטרך לצמצם איכשהו)

דרישות:
1. לבחור כמה עצים להצגה או סוג ולא רק מין. לצורך העניין יש שני סוגי מייש או שבעה סוגי ברוש. שימושים לדוגמא: אני רוצה לבחור עצי מיש מכל המינים כי הכנימה החדשה פוגעת בכולם, או לבחור  מיני עצים שלא תורמים צל (ברוש). עדיפות גבוהה. 
2. לראות אילו מינים קיימים. אני משתמש בסיסי (פעיל עצים באיפיון) וצריך את העזרה "לרענן את הזיכרון" במיני העצים הקיימים. המצב הקיים בגרסת הפיתוח של סקרול מבטא דרישה זו. עדיפות בינונית 
3.  שמות בלועזית. עדיפות נמוכה לאור הפרסונות

הצעה:
לעשות כמו בזאפ לכל מין עץ שנבחר בהתאם לנדל"ן בסרגל
<img width="728" alt="image" src="https://github.com/hasadna/treebase-app/assets/76155903/8ed59b3b-c19f-46c0-97ce-625c560095a3">

**Comment by akariv** [comment]
שים לב שיש כבר אישיו פתוח בנושא - #22. בבקשה תעבור עליהם לפני שאתה פתוח
אישיו חדש...

**Comment by akariv** [comment]
duplicate of #22
