### ISSUE TITLE
בעיה בהורדת מידע

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#52]
הורדה של: https://app.digital-forest.org.il/trees?cadaster=0&canopies=0&species=Celtis%20Sinensis&certainty=certain

![Image](https://user-images.githubusercontent.com/76155903/255426700-3c64d63f-a96c-4d10-bcc0-f4bc280336ed.png)

**Comment by akariv** [comment]
יש מצב שתספק עוד פרטים?

**Comment by akariv** [comment]
באיזו תצוגת מפה היית כשזה קרה?

**Comment by akariv** [comment]
הקטנתי את מספר העצים המקסימלי (50000 היה קצת יותר מדי לקובץ אקסל גם ככה). עכשיו עובד בלי בעיה.
