### ISSUE TITLE
סינון לפי מקור מידע

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#54]
![Image](https://github.com/hasadna/treebase-app/assets/76155903/1f69a393-316c-4a53-90f5-6e8b63f75068)

**Comment by akariv** [comment]
״הצג עצים של מפ״י שלא מופיעים אצלי״ כבר קיים במערכת.


האם יש מתאר שימוש נוסף שקשור לסינון הזה? בזמן המימוש ניסיתי להבין מה בדיוק היה הצורך פה (מעבר למה שציינתי) ולא הצלחתי להיזכר בשום דבר נוסף.

**Comment by emrib** [comment]
סינון בין מה שדווח לרשות המים ומה שיש לי בסקר (אשדוד למשל). יילך ויהיה רלוונטי ככל שנאסוף עוד מקורות מידע

**Comment by akariv** [comment]
הוסף ל״הצגת עצים:״

**Comment by emrib** [comment]
יש בעיית נדל"ן, אבל עדיף לכתוב רק עצים מזוהים שלא דווחו לרשות המים, ככה יוצא שאנחנו משנמכים בעצמנו את תועלת החשד לעץ בהקשר זה. האם ניתן להכניס במקום הקיים? @akariv
