### ISSUE TITLE
שינויים בכיסוי חופות

### ISSUE THREAD

**Issue by emrib** [hasadna/treebase-app#9]
להוסיף טולטיפ "סך החופות מסך שטח הרשות"

**Comment by akariv** [comment]
@emrib 
איפה בדיוק אמור להיות הטולטיפ?
תוכל להכניס הערה בפיגמה ולקשר לאישיו הזה?

**Comment by akariv** [comment]
קבל ביטול, ראיתי למה אתה מתכוון
